apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-v74r
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wgnv-tenant/rhtap-demo-app/hacbs-test-project-v74r@sha256:6ecee0948296e95a0f6a93824c4e5122fcb736d52520b7d71178153096418b07
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
