apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-v74r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-v74r
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-v74r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-v74r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-v74r
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wgnv-tenant/rhtap-demo-app/hacbs-test-project-v74r@sha256:9269695ec6992b132b0ba28f3aa2f4b017ccab67884b9bacbee438676c6a4b2a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
